version: '3.4'
services:
  webserver:
    container_name: shoping
    build:
      context: ../shoping
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes:
      - .:/var/www/html
    ports:
      - 5000:80
  database:
    container_name: database
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopping
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306
   
  phpmyadmin:
     container_name: phpmyadmin
     image: phpmyadmin/phpmyadmin
     ports:
       - 8080:80
     restart: always
     environment:
      PMA_HOST : database
      MYSQL_USER: root
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
       