version: "3.3"
services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: shoping
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3307:3307
        volumes:
            - ./mysql_volume_do_not_delete:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin
        container_name: php
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: db
            PMA_PORT: 3307
            MYSQL_ROOT_PASSWORD: root
        restart: always
        depends_on:
            - db
        ports:
            - 8282:82
